name: Deploy

on: push
  paths:
    - 'up_lpg/**'
    - 'setup.py'

jobs:
  build-win:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist

      - uses: actions/upload-artifact@v3
        with:
          name: windows-wheels
          path: dist/*.whl

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build manylinux Python wheels 
        uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64
        with:
          python-versions: 'cp37-cp37m'

      - uses: actions/upload-artifact@master
        with:
          name: linux-wheel
          path: dist/*-manylinux*.whl
          
  deploy-pypi:
      runs-on: ubuntu-latest
      needs: build-linux
      if: github.ref == 'refs/heads/master' # We only deploy on master commits

      steps:
        - name: Make distrib
          run: |
            python3 -m pip install wheel
            python3 setup.py sdist --format=gztar
            python3 setup.py bdist_wheel
        - uses: actions/download-artifact@master
          with:
            name: linux-wheel
            path: dist
        - uses: actions/download-artifact@master
          with:
            name: windows-wheels
            path: dist

        - name: Upload to PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}




            