name: CD

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38' 

      - uses: actions/upload-artifact@master
        with: 
          name: linux-wheel
          path: dist/*-manylinux*.whl 


  deploy-pypi:
    runs-on: ubuntu-latest
    needs: [build-linux]
    if: github.ref == 'refs/heads/master' # We only deploy on master commits

    steps:

    - uses: actions/download-artifact@master
      with:
        name: linux-wheel
        path: dist

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - run: ls dist

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}