name: Deploy

on: push

jobs:
  build-win:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@master
        with:
          python-version: 3.8  # Usa la versione 3.8 per migliore compatibilità su Windows

      - name: Set cibuildwheel options
        shell: pwsh
        run: |
          $env:CIBW_SKIP="cp37-win32"  # Salta CPython 3.7 32 bit su Windows

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist

      - uses: actions/upload-artifact@master
        with:
          name: windows-wheel
          path: dist/*.whl

      - name: Check artifact files
        run: ls dist/*.whl || echo "No wheels found in dist/"

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build manylinux Python wheels 
        uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64
        with:
          python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311 cp312-cp312'

      - uses: actions/upload-artifact@master
        with:
          name: linux-wheel
          path: dist/*-manylinux*.whl
          
  deploy-pypi:
      runs-on: ubuntu-latest
      needs: [build-linux, build-win]
      if: github.ref == 'refs/heads/master' # We only deploy on master commits

      steps:
        - name: Checkout repo
          uses: actions/checkout@master
          with:
            fetch-depth: 0

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.8

        - uses: actions/download-artifact@master
          with:
            name: linux-wheel
            path: dist

        - uses: actions/download-artifact@master
          with:
            name: windows-wheel
            path: dist

        - run: ls dist

        - name: Upload to PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}